django090524/django0123/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('index', views.page_index1, name='page-index1'),
    ]

django090524/django090524/urls.py
from django.contrib import admin
from django.urls import path, include
from djangomidleware import views as middleware_views
from djangoauth import views as djangoauth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django0123/', include('django0123.urls')),
    path('djangoform/', include('djangoform.urls')),
    path('middleware/', middleware_views.middlewareTest1, name='midtest1'),
    path('exception/', middleware_views.middlewareTest2, name='midtest2'),
    path('template/', middleware_views.middlewareTest3, name='midtest3'),
    path('auth/', include('djangoauth.urls')),
]

django090524/djangoauth/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('home/', views.home_page, name='home'),
    path('logout/', views.user_logout, name='logout'),
    ]

django090524/djangoauth/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    post_date = models.DateField(auto_now_add=True)

django090524/djangoauth/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

class CustomeUserForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password Again', widget=forms.PasswordInput)
    #customized password2 field from UserCreationForm
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        #all above are User Model Fields, except UserCreationForm will add two pwd fields automatically
        labels = {'emai':'Enter your email'}

django090524/djangoauth/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomeUserForm
from django.contrib import messages #django messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from .signals import notification
# Create your views here.

#method1 - using only UserCreationForm
def sign_up(request):
    notification.send(sender=None, request=request, user=['user1', 'user2']) #cusom signal demo
    messages = None
    if request.method == 'POST':
        userForm = UserCreationForm(request.POST)
        if userForm.is_valid():
            print('success')
            #userForm.save() 
            #logic for adding user to Post Manager group when sign up
            user = userForm.save()
            group = Group.objects.get(name='Post Manager')
            user.groups.add(group)
            #adding group logic ends
            messages = ['User Created Successfully']
    else:
        userForm = UserCreationForm()
    return render(request, 'djangoauth/signup.html', {'form':userForm, 'messages':messages})

#method2 - using customized form inheriting UserCreationForm and User Model
def customised_sign_up(request):
    messages = None
    if request.method == 'POST':
        userForm = CustomeUserForm(request.POST)
        if userForm.is_valid():
            messages.success(request, 'Account Created Successfully!')
            print('success')
            userForm.save()
    else:
        userForm = CustomeUserForm()
    return render(request, 'djangoauth/signup.html', {'form':userForm})

#use one of above form view one at time in urls.py for path 'signup/' to see the difference

def home_page(request):
    if request.user.is_authenticated:
        return render(request, 'djangoauth/home.html')
    return redirect('login')
#authentication views

#login
def user_login(request):
    #if user is not authenticated then redirect to login else redirect to Home page
    if not request.user.is_authenticated:
        if request.method == 'POST':
            loginForm = AuthenticationForm(request=request, data=request.POST)
            if loginForm.is_valid():
                uname = loginForm.cleaned_data['username']
                upwd = loginForm.cleaned_data['password']
                user = authenticate(username=uname, password=upwd)
                if user is not None:
                    login(request, user)
                    return render(request, 'djangoauth/home.html', {'user':request.user})
                    
        loginForm = AuthenticationForm()
        return render(request, 'djangoauth/login.html', {'form':loginForm})
    else:
        return redirect('home')

#logout
def user_logout(request):
    logout(request)
    return redirect('login')

django090524/djangoauth/templates/djangoauth/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Form</title>
</head>
<body>
 <h1>Welcome {{user}} Home Page after Login</h1>

    <!-- checking permssions for user to delete record from Post Model -->
    {% if perms.djangoauth.delete_post %}
    <button>Delete Post</button>
    {% endif %}
 
<button><a href='{% url "logout" %}'>logout</a></button>
</body>
</html>

django090524/djangoauth/templates/djangoauth/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Form</title>
</head>
<body>
     <!--  if form object is send -->
    {% if form %}
    <form action="" method='POST'>
        {% csrf_token %}

        <!-- Display non-field errors -->
        {% if form.non_field_errors  %}
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
        {% endif %}

        {% for field in form %}
        {{field.label_tag}} {{field}} {{field.errors |striptags}}<br><br>
        {% endfor %}
        
        <!-- Display nfield errors -->
        {% for error in field.errors %}
        {{ error }}<br>
        {% endfor %} 

        <input type='submit' value='Submit'>
    </form> 
    {% endif %}

    <br>
    <button><a href='{% url "signup" %}'>Signup</a></button>
</body>
</html>

django090524/djangoauth/templates/djangoauth/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Form</title>
</head>
<body>
    {% comment %} if form object is send {% endcomment %}
    {% if form %}
    <form action="" method='POST'>
        {% csrf_token %}
        {% for field in form %}
        {{field.label_tag}} {{field}} {{field.errors |striptags}}<br><br>
        {% endfor %}
        <input type='submit' value='Submit'>
    </form> 
    {% endif %}
    
    <br>
    <button><a href='{% url "login" %}'>Login</a></button>

    {% comment %} if user is created {% endcomment %}
    {% if messages %}
    {% for msg in messages %}
    <button {% if msg.tags %} class="{{msg.tags}}" {% endif %}> {{msg}} </button>
    {% endfor %}
    {% endif %}
</body>
</html>